import './globalDecoder'
import './timeDecoder'
import './dateDecoder'
import './imageDecoder'
import './badgeDecoder'
import './iconDecoder'
import './dataDecoder'
import './labelDecoder'
import './progressRingDecoder'
import './circleDecoder'
import './rectDecoder'
import './bluetoothDecoder'
import './disturbDecoder'
import './alarmsDecoder'
import './notificationDecoder'
import './textDecoder'

export { decodeElement, registerDecoder, getDecoder, defaultDecoder } from '../elementDecoder' 